@echo off
chcp 65001 >nul
@echo off
set URL=https://raw.githubusercontent.com/S-MpAI/Reverse-Collapse-RUS/refs/heads/main/ru/Text/_AutoGeneratedTranslations.txt
set DEST_PATH=.\ru\Text\_AutoGeneratedTranslations.txt
if not exist ".\ru\Text\" (
    mkdir ".\ru\Text\"
)
curl -L %URL% -o %DEST_PATH%
if %ERRORLEVEL% NEQ 0 (
    echo Произошла ошибка при скачивании перевода [%ERRORLEVEL%] %URL%
    pause
    exit /b %ERRORLEVEL%
)
echo Файл был успешно скачан в %DEST_PATH%
pause
